name: "Aventura"
description: "A free, open source AI adventure and creative writing app"
url: "aventura.camp"
docs: "http://aventura.camp/setup/"  
tags:
  - creative  
open_source: "https://github.com/unkarelian/Aventura"  
date_added: "2025-01-14"  
